// Default vocabulary for the site.
// Replace this file with the one downloaded from "Import lessons → Download data.js"
// once you have imported your Viber lessons.
//
// vocab:     { de, ro, type: verb | noun | adverb | connector | other, forms?: [irregular German forms] }
//            Use "/" in `ro` or `de` to list several accepted answers.
// sentences: { de, ro }  – use "|" to list several accepted translations.
window.SEED = {
  sample: true,
  vocab: [
    // Verbs
    { de: "lernen", ro: "a învăța", type: "verb" },
    { de: "sprechen", ro: "a vorbi", type: "verb", forms: ["sprichst", "spricht"] },
    { de: "wohnen", ro: "a locui", type: "verb" },
    { de: "arbeiten", ro: "a lucra / a munci", type: "verb" },
    { de: "kommen", ro: "a veni", type: "verb" },
    { de: "gehen", ro: "a merge", type: "verb" },
    { de: "trinken", ro: "a bea", type: "verb" },
    { de: "essen", ro: "a mânca", type: "verb", forms: ["isst"] },
    { de: "spielen", ro: "a juca / a se juca", type: "verb" },
    { de: "kaufen", ro: "a cumpăra", type: "verb" },
    { de: "lesen", ro: "a citi", type: "verb", forms: ["liest"] },
    { de: "schreiben", ro: "a scrie", type: "verb" },
    { de: "machen", ro: "a face", type: "verb" },
    { de: "heißen", ro: "a se numi", type: "verb" },
    { de: "brauchen", ro: "a avea nevoie de", type: "verb" },
    { de: "kochen", ro: "a găti", type: "verb" },
    { de: "hören", ro: "a auzi / a asculta", type: "verb" },
    { de: "sehen", ro: "a vedea", type: "verb", forms: ["siehst", "sieht"] },
    { de: "fahren", ro: "a merge (cu mașina) / a conduce", type: "verb", forms: ["fährst", "fährt"] },
    { de: "verstehen", ro: "a înțelege", type: "verb" },

    // Nouns
    { de: "der Hund", ro: "câinele / câine", type: "noun" },
    { de: "die Katze", ro: "pisica / pisică", type: "noun" },
    { de: "das Haus", ro: "casa / casă", type: "noun" },
    { de: "die Schule", ro: "școala / școală", type: "noun" },
    { de: "der Lehrer", ro: "profesorul / profesor", type: "noun" },
    { de: "die Lehrerin", ro: "profesoara / profesoară", type: "noun" },
    { de: "das Buch", ro: "cartea / carte", type: "noun" },
    { de: "der Tisch", ro: "masa / masă", type: "noun" },
    { de: "das Wasser", ro: "apa / apă", type: "noun" },
    { de: "der Kaffee", ro: "cafeaua / cafea", type: "noun" },
    { de: "das Brot", ro: "pâinea / pâine", type: "noun" },
    { de: "die Milch", ro: "laptele / lapte", type: "noun" },
    { de: "die Stadt", ro: "orașul / oraș", type: "noun" },
    { de: "die Arbeit", ro: "munca / muncă", type: "noun" },
    { de: "der Freund", ro: "prietenul / prieten", type: "noun" },
    { de: "die Familie", ro: "familia / familie", type: "noun" },
    { de: "die Mutter", ro: "mama / mamă", type: "noun" },
    { de: "der Vater", ro: "tatăl / tată", type: "noun" },
    { de: "der Bruder", ro: "fratele / frate", type: "noun" },
    { de: "die Schwester", ro: "sora / soră", type: "noun" },
    { de: "das Kind", ro: "copilul / copil", type: "noun" },
    { de: "das Auto", ro: "mașina / mașină", type: "noun" },
    { de: "der Zug", ro: "trenul / tren", type: "noun" },
    { de: "die Zeit", ro: "timpul / timp", type: "noun" },
    { de: "der Tag", ro: "ziua / zi", type: "noun" },
    { de: "Deutsch", ro: "germana / limba germană", type: "noun" },

    // Adverbs
    { de: "heute", ro: "azi / astăzi", type: "adverb" },
    { de: "morgen", ro: "mâine", type: "adverb" },
    { de: "gestern", ro: "ieri", type: "adverb" },
    { de: "jetzt", ro: "acum", type: "adverb" },
    { de: "hier", ro: "aici", type: "adverb" },
    { de: "dort", ro: "acolo", type: "adverb" },
    { de: "immer", ro: "mereu / întotdeauna", type: "adverb" },
    { de: "oft", ro: "des / adesea", type: "adverb" },
    { de: "gern", ro: "cu plăcere", type: "adverb" },
    { de: "sehr", ro: "foarte", type: "adverb" },
    { de: "auch", ro: "și / de asemenea", type: "adverb" },
    { de: "gut", ro: "bine", type: "adverb" },
    { de: "schnell", ro: "repede", type: "adverb" },
    { de: "langsam", ro: "încet", type: "adverb" },
    { de: "zusammen", ro: "împreună", type: "adverb" },
    { de: "wieder", ro: "din nou / iar", type: "adverb" },
    { de: "schon", ro: "deja", type: "adverb" },
    { de: "nie", ro: "niciodată", type: "adverb" },

    // Connectors
    { de: "und", ro: "și", type: "connector" },
    { de: "aber", ro: "dar", type: "connector" },
    { de: "oder", ro: "sau", type: "connector" },
    { de: "weil", ro: "pentru că / deoarece", type: "connector" },
    { de: "denn", ro: "căci / pentru că", type: "connector" },
    { de: "dass", ro: "că", type: "connector" },
    { de: "deshalb", ro: "de aceea", type: "connector" },
    { de: "dann", ro: "apoi / atunci", type: "connector" },
    { de: "wenn", ro: "dacă / când", type: "connector" },
    { de: "sondern", ro: "ci", type: "connector" },
    { de: "trotzdem", ro: "totuși", type: "connector" },

    // Other (prepositions etc.)
    { de: "in", ro: "în", type: "other" },
    { de: "mit", ro: "cu", type: "other" },
  ],

  sentences: [
    { de: "Ich lerne Deutsch.", ro: "Învăț germană.|Eu învăț germana.|Învăț limba germană." },
    { de: "Der Hund ist hier.", ro: "Câinele este aici.|Câinele e aici." },
    { de: "Wir wohnen in der Stadt.", ro: "Locuim în oraș." },
    { de: "Ich trinke Kaffee und du trinkst Wasser.", ro: "Eu beau cafea și tu bei apă." },
    { de: "Mein Vater arbeitet heute.", ro: "Tatăl meu lucrează azi.|Tatăl meu lucrează astăzi.|Tata lucrează azi." },
    { de: "Ich spreche langsam, weil ich Deutsch lerne.", ro: "Vorbesc încet pentru că învăț germană.|Vorbesc încet, pentru că învăț germana.|Vorbesc încet deoarece învăț germana." },
    { de: "Das Kind liest ein Buch.", ro: "Copilul citește o carte." },
    { de: "Meine Mutter kocht gern.", ro: "Mama mea gătește cu plăcere.|Mamei mele îi place să gătească." },
    { de: "Wir fahren morgen mit dem Zug.", ro: "Mâine mergem cu trenul.|Mergem mâine cu trenul." },
    { de: "Er kommt heute nicht, aber morgen.", ro: "El nu vine azi, dar mâine.|Nu vine azi, dar mâine.|Nu vine astăzi, dar mâine." },
    { de: "Ich habe keine Zeit.", ro: "Nu am timp.|N-am timp." },
    { de: "Die Lehrerin spricht immer langsam.", ro: "Profesoara vorbește mereu încet.|Profesoara vorbește întotdeauna încet." },
    { de: "Mein Bruder spielt oft mit dem Hund.", ro: "Fratele meu se joacă des cu câinele.|Fratele meu se joacă adesea cu câinele." },
    { de: "Sie kauft Brot und Milch.", ro: "Ea cumpără pâine și lapte." },
    { de: "Ich verstehe dich nicht.", ro: "Nu te înțeleg." },
    { de: "Wir essen zusammen.", ro: "Mâncăm împreună." },
    { de: "Ich gehe jetzt in die Schule.", ro: "Acum merg la școală.|Merg acum la școală." },
    { de: "Du schreibst sehr gut.", ro: "Scrii foarte bine." },
    { de: "Meine Schwester wohnt dort.", ro: "Sora mea locuiește acolo." },
    { de: "Ich brauche ein Auto.", ro: "Am nevoie de o mașină." },
    { de: "Die Katze ist sehr schnell.", ro: "Pisica este foarte rapidă.|Pisica e foarte rapidă." },
    { de: "Mein Freund liest oft, aber ich schreibe gern.", ro: "Prietenul meu citește des, dar eu scriu cu plăcere.|Prietenul meu citește des, dar mie îmi place să scriu." },
  ],
};
